'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Player
    Public Property PlayerID As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property DateOfBirth As Nullable(Of Date)
    Public Property Value As Nullable(Of Integer)

    Public Overridable Property TeamDetail As TeamDetail

End Class
